language: node_js
node_js:
  - "8"
  - "9"
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database test;' -U postgres
script:
  - yarn test
env:
  - DATABASE_URL=postgres://postgres@localhost/test DB_DISABLE_SSL=true