language: node_js
node_js:
  - '10'
  - '11'
addons:
  postgresql: '9.6'
before_script:
  - psql -c 'create database test;' -U postgres
  - psql -U postgres test -c "CREATE EXTENSION \"uuid-ossp\";"
  - psql -U postgres test -c "CREATE EXTENSION \"citext\";"
script:
  - yarn test
  - yarn build
  - yarn test_build
after_script:
  - yarn test --coverage
  - yarn reportCoverage
env:
  - DATABASE_URL=postgres://postgres@localhost/test MAMMOTH_DISABLE_SSL=true
