version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'
    automerged_updates:
      - match:
          # Automerge all updates to devDependencies if checks pass
          dependency_type: "development"
          update_type: "all"
      - match:
          # Automerge all patch updates e.g. 1.0.1 to 1.0.2
          dependency_type: "production"
          update_type: "semver:patch"
