name: Lint, build & test

on:
  push:
    branches:
      # These are there to make sure checks are run in branches dependabot creates. A single *
      # doesn't work so we're adding all possible cases here.
      - '*'
      - '*/*'
      - '*/*/*' # E.g dependabot/npm_and_yarn/package-name
      - '*/*/*/*' # E.g dependabot/npm_and_yarn/scope/package-name
      - '!master'

env:
  NODE_VERSION: 12.x

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
