name: Lint, build & test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x', '22.x', '24.x', '25.x']
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Make sure Mammoth version in "package-lock.json" matches "package.json"
        run: |
          version_in_package_lock_json=$(jq -r .version package-lock.json)
          version_in_package_json=$(jq -r .version package.json)
          if [[ "$version_in_package_lock_json" != "$version_in_package_json" ]]; then
            echo "ERROR: Mammoth version mismatch:" > /dev/stderr
            echo "    package.json: $version_in_package_json" > /dev/stderr
            echo "    package-lock.json: $version_in_package_lock_json" > /dev/stderr
            exit 1
          fi
      - run: npm ci
      - run: npm run build
      - run: npm test -- --coverage
        env:
          CI: true
      - run: npm run check
      - run: npm run prettier-check
